name: security
on:
 push:
   branches:
   - main
jobs:
   security
runs-on: ubuntu-latest
steps:
- name: checkout code
  uses: action/checkout@v2

- name: Run Trivy vulnerability scan in fs mode
  uses: aquasecurity/trivy-action@main
  with:
   scan-type: 'fs'
   scan-ref: '.'
   trivy-config: trivy.yaml
   format: 'table'
   severity: 'CRITICAL,HIGH'
